apiVersion: v1
kind: Service
metadata:
  name: digit-recognition
spec:
  selector:
    app: digit-app
  ports:
    - protocol: "TCP"
      port: 6000
      targetPort: 5000
      nodePort: 32372
  type: NodePort  

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: digit-app
spec:
  selector:
    matchLabels:
      app: digit-app
  replicas: 2
  template:
    metadata:
      labels:
        app: digit-app
    spec:
      containers:
        - name: digit-app
          image: docker.io/yohannesah/microservice-first
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
