apiVersion: v1
kind: Service
metadata:
  name: azure-service
spec:
  type: NodePort
  selector:
    app: azure-app
  ports:
    - port: 5002
      targetPort: 5002
      nodePort: 30003
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: azure-app
  template:
    metadata:
      labels:
        app: azure-app
    spec:
      containers:
        - name: azure-app
          image: docker.io/yohannesah/microservice-first
          ports:
            - containerPort: 5002
          env:
            - name: API_KEY
              value: "#######################"
            - name: ENDPOINT
              value: "https://api.cognitive.microsofttranslator.com/"
