apiVersion: v1
kind: Service
metadata:
  name: text-app-service
spec:
  type: NodePort
  selector:
    app: text-app
  ports:
    - port: 5001
      targetPort: 5001
      nodePort: 30001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: text-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: text-app
  template:
    metadata:
      labels:
        app: text-app
    spec:
      containers:
        - name: text-app
          image: docker.io/yohannesah/microservice-first
          ports:
            - containerPort: 5001
