apiVersion: apps/v1
kind: Deployment
metadata:
  name: text-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: text-app
  template:
    metadata:
      labels:
        app: text-app
    spec:
      containers:
        - name: text-app
          image: docker.io/yohannesah/microservice-first
          env:
            - name: DIGIT_RECOGNITION_URL
              value: "http://digit-recognition:6000"  # Update the URL here
          ports:
            - containerPort: 5001
