apiVersion: v1
kind: Service
metadata:
  name: speech-service
spec:
  type: NodePort
  selector:
    app: speech-app
  ports:
    - port: 5004
      targetPort: 5004
      nodePort: 30007
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: speech-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: speech-app
  template:
    metadata:
      labels:
        app: speech-app
    spec:
      containers:
        - name: speech-app
          image: docker.io/yohannesah/microservice-first
          ports:
            - containerPort: 5004
          env:
            - name: SPEECH_KEY
              value: ########################
            - name: SPEECH_REGION
              value: westeurope
